# Generated by Django 3.0.5 on 2020-05-17 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artist_name',
            new_name='language',
        ),
        migrations.RemoveField(
            model_name='album',
            name='genre',
        ),
    ]
