# Generated by Django 3.0.5 on 2020-05-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20200517_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='language',
            field=models.FileField(upload_to=''),
        ),
    ]
