# Generated by Django 3.0.5 on 2020-05-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20200517_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
