# Generated by Django 3.0.5 on 2020-05-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_auto_20200520_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
