# Generated by Django 3.0.5 on 2020-05-20 18:15

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_auto_20200520_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.ImageField(blank=True, default=music.models.logo_default, null=True, upload_to=''),
        ),
    ]
